// Bu dosya, uygulamanın en üst düzey düzenini tanımlayan Kök Düzen (Root Layout) dosyasıdır.
// Tüm sayfa ve bileşenleri burada tanımlanan yapının içinde yer alır.

import type { Metadata } from "next";
// Geist ve Geist_Mono yazı tiplerini içe aktarıyorum.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// NextAuth'ın oturum sağlayıcısını (Session Provider) içe aktarıyorum.
// Bu, tüm alt bileşenlerin oturum verisine erişimini sağlıyor.
import NextAuthSessionProvider from './providers/next-auth-provider';

// Geist yazı tipleri için değişkenleri tanımlıyoruz.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Sayfa için meta verilerini (başlık, açıklama vb.) tanımlıyorum.
// Bu veriler SEO ve tarayıcı sekmesi için önemlidir.
export const metadata: Metadata = {
  title: "Next-auth-project",
  description: "Generated by create next app",
};

// Kök Düzen Bileşeni (Root Layout Component)
// Bu bileşen, tüm sayfaları ve bileşenleri sarmalar.
export default function RootLayout({
  children, // children, altındaki tüm sayfa ve bileşenleri temsil eder.
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html> etiketi, uygulamanın genel dilini ve yazı tipi değişkenlerini belirler.
    <html lang="en">
      {/* <body> etiketi, uygulamanın tüm içeriğini barındırır. */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* NextAuthSessionProvider bileşeni, uygulamanın tamamını sarmalar.
                Bu, uygulamanın herhangi bir yerinden oturum verisine erişilmesini
                ve kimlik doğrulama işlemlerinin yapılmasını mümkün kılar.
                */}
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}